# Generated by Django 3.1.2 on 2020-11-26 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontoatendimento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedimento', models.IntegerField(choices=[('1', 'Consulta'), ('2', 'Retorno'), ('3', 'Enfermaria')])),
                ('medicacao', models.CharField(blank=True, max_length=200, null=True)),
                ('receitas', models.CharField(blank=True, max_length=200, null=True)),
                ('exames', models.CharField(blank=True, max_length=200, null=True)),
                ('queixa', models.CharField(blank=True, max_length=200, null=True)),
                ('doencas', models.CharField(blank=True, max_length=200, null=True)),
                ('hipotese', models.CharField(blank=True, max_length=200, null=True)),
                ('diagnostico', models.CharField(blank=True, max_length=200, null=True)),
                ('observacoes', models.CharField(blank=True, max_length=200, null=True)),
                ('data_atendimento', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='datanasc',
            field=models.DateField(blank=True, null=True),
        ),
    ]
