# Generated by Django 3.1.2 on 2020-11-26 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontoatendimento', '0003_auto_20201125_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='procedimento',
            field=models.IntegerField(choices=[(1, 'Consulta'), (2, 'Retorno'), (3, 'Enfermaria')]),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
