# Generated by Django 3.1.2 on 2020-11-26 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prontoatendimento', '0004_auto_20201125_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prontoatendimento.medico'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prontoatendimento.paciente'),
        ),
    ]
